stages:
  - staging-build
  - staging-deploy
  - staging-clean
  - prod-build
  - prod-deploy
  - prod-clean

test-build-job:
  stage: staging-build
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"
  tags:
    - srv-staging
  script:
    - cd /home/admin/docker/weu1/ws-template/ && sudo docker-compose build --no-cache

test-deploy-job:
  stage: staging-deploy
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"
  tags:
    - srv-staging
  script:
    - cd /home/admin/docker/weu1/ws-template/ && sudo docker-compose up -d

test-clean-job:
  stage: staging-clean
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"
  tags:
    - srv-staging
  script:
    - sudo docker image prune --force

prod-build-job:
  stage: prod-build
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == "prod"
  tags:
    - srv-prod
  script:
    - cd /home/admin/docker/weu1/ws-template/ && sudo docker-compose build --no-cache

prod-deploy-job:
  stage: prod-deploy
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == "prod"
  tags:
    - srv-prod
  script:
    - cd /home/admin/docker/weu1/ws-template/ && sudo docker-compose up -d

prod-clean-job:
  stage: prod-clean
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == "prod"
  tags:
    - srv-prod
  script:
    - sudo docker image prune --force
